export const blogs = [
    {
      date: "5th January, 2026",
      title: "My Journey into Tech: Thoughts, people and life",
      content: `My path has been anything but linear. I once envisioned myself as a chartered accountant or economist, ideally working at Deloitte. The idea of analyzing financial statements and helping businesses thrive appealed to me for years. So, it was natural for me to apply to universities, hoping to study something in line with those ambitions.
          When the University of Ghana accepted me into their Mathematical Sciences program, rather than my first choice, I was initially conflicted. The alternative was to accept my offer at KNUST, where I had been admitted into my preferred field. After much thought and family encouragement, I decided to embrace Mathematical Sciences at UG.
          Not long after that decision, an unexpected twist occurred—I was offered admission into my first choice of study after all. It would have been easy to switch, but this time, I felt a pull toward something different. I stayed the course, and now, looking back, I realize that was one of the best decisions I’ve made.
          The turning point came when I met my mentor, Zenas Awuku. Zenas, a software engineer, introduced me to the world of coding and problem-solving in ways I hadn’t considered before. His mentorship reshaped my academic focus and opened a door to new possibilities. I began to explore Python, mainly because Zenas assured me it was a gentle yet powerful language to start with. He was right. The simplicity of Python not only helped me build confidence, but it also laid the foundation for what has become a genuine passion for programming and, potentially, AI/ML.
          Interestingly, my first brush with tech wasn’t in university—it was in high school, where I joined the ICT club. I picked up HTML and CSS, learning the basics of web development. But it wasn’t until after high school, during a break after WASSCE, that I really dove into coding. Despite the limitations of not having a laptop at the time, I tinkered with web development. My initial progress caught Zenas’s attention. He admired my effort, which motivated me even more. Every step and every challenge taught me perseverance.
          Zenas introduced me to Global Code, where I attended a boot camp with two peers. It was there that my love for technology deepened. I also attended PyCon Africa, where I joined the Django Girls session. Through the Django Girls session, I built a Django-powered website—a moment that felt like a full-circle realization of how far I had come. That website is now home to my portfolio.
          The transition from numbers and theories to code and algorithms hasn’t been without doubt. Balancing the rigorous demands of my studies with my passion for tech has, at times, been overwhelming. Yet, the support I’ve received from people like Zenas and my lecturers—especially Dr. Ken and Mr. Ayanful—has been invaluable. Their encouragement has made my Level 100 experience more fulfilling than I could have imagined.
          Looking back, I see how each twist in the road has brought me closer to where I am today. I know there’s still a long way to go, and the late nights spent on assignments, tasks, and studying are just part of the journey. I believe this persistence will pay off, and I am excited to see where this new direction leads.
          Tech might not have been my first love, but it has certainly become one of my greatest passions.`
    },
    {
      date: "5th January, 2026",
      title: "My Journey",
      content: `My path has been anything but linear. I once envisioned myself as a chartered accountant or economist, ideally working at Deloitte. The idea of analyzing financial statements and helping businesses thrive appealed to me for years. So, it was natural for me to apply to universities, hoping to study something in line with those ambitions.
          When the University of Ghana accepted me into their Mathematical Sciences program, rather than my first choice, I was initially conflicted. The alternative was to accept my offer at KNUST, where I had been admitted into my preferred field. After much thought and family encouragement, I decided to embrace Mathematical Sciences at UG.
          Not long after that decision, an unexpected twist occurred—I was offered admission into my first choice of study after all. It would have been easy to switch, but this time, I felt a pull toward something different. I stayed the course, and now, looking back, I realize that was one of the best decisions I’ve made.
          The turning point came when I met my mentor, Zenas Awuku. Zenas, a software engineer, introduced me to the world of coding and problem-solving in ways I hadn’t considered before. His mentorship reshaped my academic focus and opened a door to new possibilities. I began to explore Python, mainly because Zenas assured me it was a gentle yet powerful language to start with. He was right. The simplicity of Python not only helped me build confidence, but it also laid the foundation for what has become a genuine passion for programming and, potentially, AI/ML.
          Interestingly, my first brush with tech wasn’t in university—it was in high school, where I joined the ICT club. I picked up HTML and CSS, learning the basics of web development. But it wasn’t until after high school, during a break after WASSCE, that I really dove into coding. Despite the limitations of not having a laptop at the time, I tinkered with web development. My initial progress caught Zenas’s attention. He admired my effort, which motivated me even more. Every step and every challenge taught me perseverance.
          Zenas introduced me to Global Code, where I attended a boot camp with two peers. It was there that my love for technology deepened. I also attended PyCon Africa, where I joined the Django Girls session. Through the Django Girls session, I built a Django-powered website—a moment that felt like a full-circle realization of how far I had come. That website is now home to my portfolio.
          The transition from numbers and theories to code and algorithms hasn’t been without doubt. Balancing the rigorous demands of my studies with my passion for tech has, at times, been overwhelming. Yet, the support I’ve received from people like Zenas and my lecturers—especially Dr. Ken and Mr. Ayanful—has been invaluable. Their encouragement has made my Level 100 experience more fulfilling than I could have imagined.
          Looking back, I see how each twist in the road has brought me closer to where I am today. I know there’s still a long way to go, and the late nights spent on assignments, tasks, and studying are just part of the journey. I believe this persistence will pay off, and I am excited to see where this new direction leads.
          Tech might not have been my first love, but it has certainly become one of my greatest passions.`
    },
    {
      date: "5th January, 2026",
      title: "My Journey",
      content: `My path has been anything but linear. I once envisioned myself as a chartered accountant or economist, ideally working at Deloitte. The idea of analyzing financial statements and helping businesses thrive appealed to me for years. So, it was natural for me to apply to universities, hoping to study something in line with those ambitions.
          When the University of Ghana accepted me into their Mathematical Sciences program, rather than my first choice, I was initially conflicted. The alternative was to accept my offer at KNUST, where I had been admitted into my preferred field. After much thought and family encouragement, I decided to embrace Mathematical Sciences at UG.
          Not long after that decision, an unexpected twist occurred—I was offered admission into my first choice of study after all. It would have been easy to switch, but this time, I felt a pull toward something different. I stayed the course, and now, looking back, I realize that was one of the best decisions I’ve made.
          The turning point came when I met my mentor, Zenas Awuku. Zenas, a software engineer, introduced me to the world of coding and problem-solving in ways I hadn’t considered before. His mentorship reshaped my academic focus and opened a door to new possibilities. I began to explore Python, mainly because Zenas assured me it was a gentle yet powerful language to start with. He was right. The simplicity of Python not only helped me build confidence, but it also laid the foundation for what has become a genuine passion for programming and, potentially, AI/ML.
          Interestingly, my first brush with tech wasn’t in university—it was in high school, where I joined the ICT club. I picked up HTML and CSS, learning the basics of web development. But it wasn’t until after high school, during a break after WASSCE, that I really dove into coding. Despite the limitations of not having a laptop at the time, I tinkered with web development. My initial progress caught Zenas’s attention. He admired my effort, which motivated me even more. Every step and every challenge taught me perseverance.
          Zenas introduced me to Global Code, where I attended a boot camp with two peers. It was there that my love for technology deepened. I also attended PyCon Africa, where I joined the Django Girls session. Through the Django Girls session, I built a Django-powered website—a moment that felt like a full-circle realization of how far I had come. That website is now home to my portfolio.
          The transition from numbers and theories to code and algorithms hasn’t been without doubt. Balancing the rigorous demands of my studies with my passion for tech has, at times, been overwhelming. Yet, the support I’ve received from people like Zenas and my lecturers—especially Dr. Ken and Mr. Ayanful—has been invaluable. Their encouragement has made my Level 100 experience more fulfilling than I could have imagined.
          Looking back, I see how each twist in the road has brought me closer to where I am today. I know there’s still a long way to go, and the late nights spent on assignments, tasks, and studying are just part of the journey. I believe this persistence will pay off, and I am excited to see where this new direction leads.
          Tech might not have been my first love, but it has certainly become one of my greatest passions.`
    }
  ];